### ISSUE TITLE
Missing Textures - 1.19.2 Forge

### ISSUE THREAD

**Issue by celsiusqc** [N1nn1/frozen_up#7]
![image](https://user-images.githubusercontent.com/63996164/206244685-40de8c2e-c708-44f8-acf9-14ebe6f41139.png)
![image](https://user-images.githubusercontent.com/63996164/206244708-d3798479-85ec-453e-9c68-71eafabdafb1.png)
![image](https://user-images.githubusercontent.com/63996164/206244739-891a12d5-bece-4ee5-bb09-437a808815a5.png)

**Comment by 0rc1nus** [comment]
Fixed in 2.1.1+
